### ISSUE TITLE
Uncaught ReferenceError: dirname is not defined

### ISSUE THREAD

**Issue by brendanlong** [314eter/atom-ocaml-indent#4]
**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [ocaml-indent](https://github.com/314eter/atom-ocaml-indent) package, v0.5.3

### Stack Trace

Uncaught ReferenceError: dirname is not defined

```
At /Users/blong/.atom/packages/ocaml-indent/lib/main.coffee:34

ReferenceError: dirname is not defined
    at Object.indentRange (/Users/blong/.atom/packages/ocaml-indent/lib/main.coffee:34:11)
    at Object.indentSelection (/Users/blong/.atom/packages/ocaml-indent/lib/main.coffee:49:8)
    at atom-text-editor.subscriptions.add.atom.commands.add.ocaml-indent:selection (/Users/blong/.atom/packages/ocaml-indent/lib/main.coffee:12:37)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by brendanlong** [comment]
I think the problem might be that this needs to be `path.dirname`?

**Comment by 314eter** [comment]
Indeed, thanks.
