### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by corvinusz** [314eter/atom-ocaml-indent#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.4.16
**OS**: "Arch Linux"
**Thrown From**: [ocaml-indent](https://github.com/314eter/atom-ocaml-indent) package 0.6.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /usr/lib/atom/src/buffered-process.js:376

Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:392:9)
    at BufferedProcess.spawn (/usr/lib/atom/src/buffered-process.js:305:51)
    at BufferedProcess.start (/usr/lib/atom/src/buffered-process.js:111:14)
    at new BufferedProcess (/usr/lib/atom/src/buffered-process.js:96:12)
    at /packages/ocaml-indent/lib/main.coffee:62:16
    at Object.ocpIndent (/packages/ocaml-indent/lib/main.coffee:56:9)
    at Object.indentRange (/packages/ocaml-indent/lib/main.coffee:35:6)
    at /packages/ocaml-indent/lib/main.coffee:28:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at /usr/lib/atom/src/text-editor.js:1127:25
    at /usr/lib/atom/src/text-editor.js:1161:28
    at TextBuffer.module.exports.TextBuffer.transact (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/lib/atom/src/text-editor.js:1594:26)
    at /usr/lib/atom/src/text-editor.js:1155:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/lib/atom/src/text-editor.js:2572:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/lib/atom/src/text-editor.js:2534:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/lib/atom/src/text-editor.js:1153:19)
    at TextEditor.module.exports.TextEditor.insertText (/usr/lib/atom/src/text-editor.js:1119:19)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/lib/atom/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/usr/lib/atom/src/text-editor-component.js:484:26)
    at HTMLDivElement.<anonymous> (/usr/lib/atom/src/text-editor-component.js:3:59)
```

### Commands

```
  4x -2:07.7.0 core:move-left (input.hidden-input)
  3x -2:04.3.0 core:move-right (input.hidden-input)
     -1:54.4.0 core:move-down (input.hidden-input)
  5x -1:53.7.0 core:move-right (input.hidden-input)
  3x -1:52.3.0 core:move-left (input.hidden-input)
  4x -0:13.5.0 core:move-down (input.hidden-input)
     -0:12.4.0 intentions:highlight (input.hidden-input)
     -0:12.3.0 editor:move-to-end-of-word (input.hidden-input)
  2x -0:11.9.0 core:move-left (input.hidden-input)
  3x -0:11.4.0 core:delete (input.hidden-input)
     -0:09.7.0 core:move-down (input.hidden-input)
  3x -0:09.4.0 core:delete (input.hidden-input)
     -0:08.6.0 core:move-up (input.hidden-input)
     -0:06.6.0 core:move-down (input.hidden-input)
  3x -0:05.5.0 core:move-left (input.hidden-input)
     -0:02.9.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-hg 2.0.14 
autoclose-html 0.23.0 
busy-signal 1.4.1 
csslint 1.1.5 
file-icons 2.1.4 
git-plus 7.8.0 
go-plus 5.5.2 
go-signature-statusbar 1.2.0 
intentions 1.1.2 
language-awk 0.1.12 
language-docker 1.1.7 
language-generic-config 1.3.0 
language-nginx 0.7.3 
language-ocaml 1.8.0 
linter 2.1.4 
linter-ui-default 1.2.4 
monokai-seti 0.7.0 
motepair2 0.37.0 
ocaml-indent 0.6.0 
ocaml-merlin 0.14.3 
output-panel 0.1.4 
todo-show 1.11.0 
tree-ignore 0.6.2 
```

**Comment by 314eter** [comment]
Do you have `ocp-indent` installed and in your PATH?

**Comment by corvinusz** [comment]
Oh, this should be closed till required investigations being done.
Perhaps this is not a package related issue.
Thank you anycase.
